/app
    layout.tsx
    page.tsx
   /dashboard
      page.tsx
   /api
      /alarm
      /machine
      /notification
      /setting
/components
   /layout
        /navbar.tsx
        /mode-toggle.tsx
        /notification-bell.tsx
   counter-card.tsx
   machine-status.tsx
   production-card.tsx
   speed-card.tsx
   websocket-status.tsx

/lib
   db.ts
   websocket.ts
/types
   machine.ts
   notification.ts
   websocket.ts